#include "html.h"
#include <ctype.h>
#include <string.h>
static int tag(const char *s,size_t n,const char *x){size_t i,m=strlen(x);if(n<m)return 0;for(i=0;i<m;i++)if(tolower((unsigned char)s[i])!=x[i])return 0;return n==m||isspace((unsigned char)s[m])||s[m]=='/';}
static void put(char *s,size_t cap,size_t *n,char c,int *cut){if(*n+1<cap)s[(*n)++]=c;else *cut=1;}
static void space(char *s,size_t cap,size_t *n,int *cut){if(*n&&s[*n-1]!=' ')put(s,cap,n,' ',cut);}
static size_t entity(const char*s,size_t n,char*o){if(n>=4&&!strncmp(s,"amp;",4)){*o='&';return 4;}if(n>=3&&!strncmp(s,"lt;",3)){*o='<';return 3;}if(n>=3&&!strncmp(s,"gt;",3)){*o='>';return 3;}return 0;}
static void href(const char*s,size_t n,char*o){size_t i=0,u=0;o[0]=0;while(i+5<n){if(!strncmp(s+i,"href=",5)){i+=5;if(s[i]=='\''||s[i]=='\"'){char q=s[i++];while(i<n&&s[i]!=q&&u+1<NB_DOCUMENT_URL_MAX)o[u++]=s[i++];}else while(i<n&&!isspace((unsigned char)s[i])&&s[i]!='>'&&u+1<NB_DOCUMENT_URL_MAX)o[u++]=s[i++];o[u]=0;return;}++i;}}
int nb_html_parse(const char *h,size_t z,NB_Document*d){size_t i=0,u=0,t=0;int title=0,skip=0,link=0;if(!h||!d)return 0;memset(d,0,sizeof*d);while(i<z){if(h[i]=='<'){size_t b=++i;int close=0;if(i<z&&h[i]=='/'){close=1;b=++i;}while(i<z&&h[i]!='>')++i;if(i==z)break;if(tag(h+b,i-b,"title"))title=!close;else if(tag(h+b,i-b,"script")||tag(h+b,i-b,"style"))skip=!close;else if(tag(h+b,i-b,"p")||tag(h+b,i-b,"br")||tag(h+b,i-b,"div")||tag(h+b,i-b,"li"))space(d->text,sizeof d->text,&u,&d->truncated);else if(tag(h+b,i-b,"a")){if(close)link=0;else if(d->link_count<NB_DOCUMENT_LINKS_MAX){href(h+b,i-b,d->links[d->link_count].href);if(d->links[d->link_count].href[0]){link=1;++d->link_count;}}}++i;continue;}if(!skip){char c=h[i++];size_t e;if(c=='&'&&(e=entity(h+i,z-i,&c)))i+=e;if(title){if(!isspace((unsigned char)c))put(d->title,sizeof d->title,&t,c,&d->truncated);}else if(isspace((unsigned char)c))space(d->text,sizeof d->text,&u,&d->truncated);else{put(d->text,sizeof d->text,&u,c,&d->truncated);if(link&&d->link_count){NB_Link*l=&d->links[d->link_count-1];size_t q=strlen(l->label);if(q+1<sizeof l->label){l->label[q]=c;l->label[q+1]=0;}}}}else ++i;}while(u&&d->text[u-1]==' ')--u;d->text[u]=0;d->title[t]=0;return 1;}
