# Patch only the build-tree checkout of pinned Mbed TLS 3.6.6.
if(NOT DEFINED NB_MBEDTLS_SOURCE_DIR)
  message(FATAL_ERROR "NB_MBEDTLS_SOURCE_DIR is required")
endif()
set(entropy_file "${NB_MBEDTLS_SOURCE_DIR}/library/entropy_poll.c")
set(library_cmake "${NB_MBEDTLS_SOURCE_DIR}/library/CMakeLists.txt")
file(READ "${entropy_file}" entropy_source)
string(FIND "${entropy_source}" "#include <bcrypt.h>" bcrypt_marker)
if(NOT bcrypt_marker EQUAL -1)
  string(FIND "${entropy_source}" "#if defined(_WIN32) &&" windows_start)
  string(FIND "${entropy_source}" "#else /* _WIN32 &&" windows_end)
  if(windows_start EQUAL -1 OR windows_end EQUAL -1 OR windows_end LESS windows_start)
    message(FATAL_ERROR "Mbed TLS entropy source changed; refusing an unsafe patch")
  endif()
  string(SUBSTRING "${entropy_source}" 0 ${windows_start} before_windows)
  string(SUBSTRING "${entropy_source}" ${windows_end} -1 after_windows)
  set(xp_entropy "#if defined(_WIN32) && !defined(EFIX64) && !defined(EFI32)\n#include <windows.h>\n#include <wincrypt.h>\nint mbedtls_platform_entropy_poll(void *data, unsigned char *output, size_t len, size_t *olen)\n{\n    HCRYPTPROV provider;\n    int ok;\n    (void) data;\n    *olen = 0;\n    if (len > 0xffffffffUL) return MBEDTLS_ERR_ENTROPY_SOURCE_FAILED;\n    if (!CryptAcquireContextW(&provider, NULL, NULL, PROV_RSA_FULL,\n                               CRYPT_VERIFYCONTEXT | CRYPT_SILENT))\n        return MBEDTLS_ERR_ENTROPY_SOURCE_FAILED;\n    ok = CryptGenRandom(provider, (DWORD) len, output);\n    CryptReleaseContext(provider, 0);\n    if (!ok) return MBEDTLS_ERR_ENTROPY_SOURCE_FAILED;\n    *olen = len;\n    return 0;\n}\n")
  file(WRITE "${entropy_file}" "${before_windows}${xp_entropy}${after_windows}")
else()
  string(FIND "${entropy_source}" "CryptGenRandom(provider" patched_marker)
  if(patched_marker EQUAL -1)
    message(FATAL_ERROR "Mbed TLS entropy patch not applied and bcrypt marker absent")
  endif()
endif()
file(READ "${library_cmake}" build_source)
string(FIND "${build_source}" "ws2_32 bcrypt)" link_marker)
if(NOT link_marker EQUAL -1)
  string(REPLACE "ws2_32 bcrypt)" "ws2_32 advapi32)" build_source "${build_source}")
  file(WRITE "${library_cmake}" "${build_source}")
else()
  string(FIND "${build_source}" "ws2_32 advapi32)" patched_link)
  if(patched_link EQUAL -1)
    message(FATAL_ERROR "Mbed TLS Windows link dependencies changed; audit required")
  endif()
endif()
